insert into tax (taxPercentage) values (24);
insert into tax (taxPercentage) values (14);
insert into tax (taxPercentage) values (10);
insert into tax (taxPercentage) values (0);

insert into size (size) values("XS");
insert into size (size) values("S");
insert into size (size) values("M");
insert into size (size) values("L");
insert into size (size) values("XL");
insert into size (size) values("XXL");
insert into size (size) values("XXXL");

insert into color (productColor) values("White");
insert into color (productColor) values("Black");
insert into color (productColor) values("Green");
insert into color (productColor) values("Blue");
insert into color (productColor) values("Red");
insert into color (productColor) values("Yellow");
insert into color (productColor) values("Fuchsia");
insert into color (productColor) values("Silver");
insert into color (productColor) values("Gray");
insert into color (productColor) values("Olive");
insert into color (productColor) values("Purple");
insert into color (productColor) values("Maroon");
insert into color (productColor) values("Aqua");
insert into color (productColor) values("Lime");
insert into color (productColor) values("Teal");
insert into color (productColor) values("Navy");

insert into province (provinceName) values("Pirkanmaan_maakunta");
insert into province (provinceName) values("Etelä-Pohjanmaan_maakunta");
insert into province (provinceName) values("Uudenmaan_maakunta");
insert into province (provinceName) values("Kanta-Hämeen_maakunta");
insert into province (provinceName) values("Pohjois-Pohjanmaan_maakunta");
insert into province (provinceName) values("Kymenlaakson_maakunta");
insert into province (provinceName) values("Satakunnan_maakunta");
insert into province (provinceName) values("Päijät-Hämeen_maakunta");
insert into province (provinceName) values("Pohjois-Savon_maakunta");
insert into province (provinceName) values("Etelä-Karjalan_maakunta");
insert into province (provinceName) values("Pohjois-Karjalan_maakunta");
insert into province (provinceName) values("Keski-Suomen_maakunta");
insert into province (provinceName) values("Varsinais-Suomen_maakunta");
insert into province (provinceName) values("Kainuun_maakunta");
insert into province (provinceName) values("Keski-Pohjanmaan_maakunta");
insert into province (provinceName) values("Pohjanmaan_maakunta");
insert into province (provinceName) values("Lapin_maakunta");
insert into province (provinceName) values("Ahvenanmaan_maakunta");
insert into province (provinceName) values("Etelä-Savon_maakunta");


insert into city (cityName, provinceId) values("Akaa",1);
insert into city (cityName, provinceId) values("Alajärvi",2);
insert into city (cityName, provinceId) values("Alavus",2);
insert into city (cityName, provinceId) values("Espoo",3);
insert into city (cityName, provinceId) values("Forssa",4);
insert into city (cityName, provinceId) values("Haapajärvi",5);
insert into city (cityName, provinceId) values("Haapavesi",5);
insert into city (cityName, provinceId) values("Hamina",6);
insert into city (cityName, provinceId) values("Hanko",3);
insert into city (cityName, provinceId) values("Harjavalta",7);
insert into city (cityName, provinceId) values("Heinola",8);
insert into city (cityName, provinceId) values("Helsinki",3);
insert into city (cityName, provinceId) values("Huittinen",7);
insert into city (cityName, provinceId) values("Hyvinkää",3);
insert into city (cityName, provinceId) values("Hämeenlinna",4);
insert into city (cityName, provinceId) values("Iisalmi",9);
insert into city (cityName, provinceId) values("Ikaalinen",1);
insert into city (cityName, provinceId) values("Imatra",10);
insert into city (cityName, provinceId) values("Joensuu",11);
insert into city (cityName, provinceId) values("Jyväskylä",12);
insert into city (cityName, provinceId) values("Jämsä",12);
insert into city (cityName, provinceId) values("Järvenpää",3);
insert into city (cityName, provinceId) values("Kaarina",13);
insert into city (cityName, provinceId) values("Kajaani",14);
insert into city (cityName, provinceId) values("Kalajoki",5);
insert into city (cityName, provinceId) values("Kangasala",1);
insert into city (cityName, provinceId) values("Kankaanpää",7);
insert into city (cityName, provinceId) values("Kannus",15);
insert into city (cityName, provinceId) values("Karkkila",3);
insert into city (cityName, provinceId) values("Kaskinen",16);
insert into city (cityName, provinceId) values("Kauhajoki",2);
insert into city (cityName, provinceId) values("Kauhava",2);
insert into city (cityName, provinceId) values("Kauniainen",3);
insert into city (cityName, provinceId) values("Kemi",17);
insert into city (cityName, provinceId) values("Kemijärvi",17);
insert into city (cityName, provinceId) values("Kerava",3);
insert into city (cityName, provinceId) values("Keuruu",12);
insert into city (cityName, provinceId) values("Kitee",11);
insert into city (cityName, provinceId) values("Kiuruvesi",9);
insert into city (cityName, provinceId) values("Kokemäki",7);
insert into city (cityName, provinceId) values("Kokkola",15);
insert into city (cityName, provinceId) values("Kotka",6);
insert into city (cityName, provinceId) values("Kouvola",6);
insert into city (cityName, provinceId) values("Kristiinankaupunki",16);
insert into city (cityName, provinceId) values("Kuhmo",14);
insert into city (cityName, provinceId) values("Kuopio",9);
insert into city (cityName, provinceId) values("Kurikka",2);
insert into city (cityName, provinceId) values("Kuusamo",5);
insert into city (cityName, provinceId) values("Lahti",8);
insert into city (cityName, provinceId) values("Laitila",13);
insert into city (cityName, provinceId) values("Lappeenranta",10);
insert into city (cityName, provinceId) values("Lapua",2);
insert into city (cityName, provinceId) values("Lieksa",11);
insert into city (cityName, provinceId) values("Lohja",3);
insert into city (cityName, provinceId) values("Loimaa",13);
insert into city (cityName, provinceId) values("Loviisa",3);
insert into city (cityName, provinceId) values("Maarianhamina",18);
insert into city (cityName, provinceId) values("Mikkeli",19);
insert into city (cityName, provinceId) values("Mänttä-Vilppula",1);
insert into city (cityName, provinceId) values("Naantali",13);
insert into city (cityName, provinceId) values("Nivala",5);
insert into city (cityName, provinceId) values("Nokia",1);
insert into city (cityName, provinceId) values("Nurmes",11);
insert into city (cityName, provinceId) values("Närpiö",16);
insert into city (cityName, provinceId) values("Orimattila",8);
insert into city (cityName, provinceId) values("Orivesi",1);
insert into city (cityName, provinceId) values("Oulainen",5);
insert into city (cityName, provinceId) values("Oulu",5);
insert into city (cityName, provinceId) values("Outokumpu",11);
insert into city (cityName, provinceId) values("Paimio",13);
insert into city (cityName, provinceId) values("Parainen",13);
insert into city (cityName, provinceId) values("Parkano",1);
insert into city (cityName, provinceId) values("Pieksämäki",19);
insert into city (cityName, provinceId) values("Pietarsaari",16);
insert into city (cityName, provinceId) values("Pori",7);
insert into city (cityName, provinceId) values("Porvoo",3);
insert into city (cityName, provinceId) values("Pudasjärvi",5);
insert into city (cityName, provinceId) values("Pyhäjärvi",5);
insert into city (cityName, provinceId) values("Raahe",5);
insert into city (cityName, provinceId) values("Raasepori",3);
insert into city (cityName, provinceId) values("Raisio",13);
insert into city (cityName, provinceId) values("Rauma",7);
insert into city (cityName, provinceId) values("Riihimäki",4);
insert into city (cityName, provinceId) values("Rovaniemi",17);
insert into city (cityName, provinceId) values("Saarijärvi",12);
insert into city (cityName, provinceId) values("Salo",13);
insert into city (cityName, provinceId) values("Sastamala",1);
insert into city (cityName, provinceId) values("Savonlinna",19);
insert into city (cityName, provinceId) values("Seinäjoki",2);
insert into city (cityName, provinceId) values("Somero",13);
insert into city (cityName, provinceId) values("Suonenjoki",9);
insert into city (cityName, provinceId) values("Tampere",1);
insert into city (cityName, provinceId) values("Tornio",17);
insert into city (cityName, provinceId) values("Turku",13);
insert into city (cityName, provinceId) values("Ulvila",7);
insert into city (cityName, provinceId) values("Uusikaarlepyy",16);
insert into city (cityName, provinceId) values("Uusikaupunki",13);
insert into city (cityName, provinceId) values("Vaasa",16);
insert into city (cityName, provinceId) values("Valkeakoski",1);
insert into city (cityName, provinceId) values("Vantaa",3);
insert into city (cityName, provinceId) values("Varkaus",9);
insert into city (cityName, provinceId) values("Viitasaari",12);
insert into city (cityName, provinceId) values("Virrat",1);
insert into city (cityName, provinceId) values("Ylivieska",5);
insert into city (cityName, provinceId) values("Ylöjärvi",1);
insert into city (cityName, provinceId) values("Ähtäri",2);
insert into city (cityName, provinceId) values("Äänekoski",12);

insert into user (email,username,password,firstName,lastName,phonenumber,created,lastLogin,deleted,admin) values ("eemeli.antikainen@gmail.com","Eemeli","", "Eemeli","Antikainen","0409606973",'2022-10-1 18:00:00','2022-10-1 18:00:00',0,1);

insert into Location (userId,cityId,address,postalCode) values (1,46,"Presidentinkatu 5", "70400");

insert into post (label,price,description,sleeveLength,material,discount,length,deleted,deliveryDaysEstimateStarting,deliveryDaysEstimateEnding,colorId,sizeId,taxId,userId) values ("T-Paita",25.50,"Perus t-paita täysin musta","10cm","Villa, Muovi","20","80cm",0,3,10,1,3,1,1);
insert into post (label,price,description,sleeveLength,material,length,deleted,deliveryDaysEstimateStarting,deliveryDaysEstimateEnding,colorId,sizeId,taxId,userId) values ("T-Paita",26.00,"Perus hyvä t-paita","10cm","Villa","80cm",0,3,10,2,3,1,1);
insert into post (label,price,description,sleeveLength,material,length,deleted,deliveryDaysEstimateStarting,deliveryDaysEstimateEnding,colorId,sizeId,taxId,userId) values ("Huppari",50,"Pehmee lämmin tyylikäs huppari","50cm","Villa","120cm",0,5,15,4,4,1,1);
insert into post (label,price,description,sleeveLength,material,discount,length,deleted,deliveryDaysEstimateStarting,deliveryDaysEstimateEnding,colorId,sizeId,taxId,userId) values ("Tiukat housut",15,"Tiukat mustat spandex housut","50cm","Spandex","20","120cm",0,1,3,1,1,1,1);

insert into orderstatus (status) values ("Order received");
insert into orderstatus (status) values ("Order delivered");
insert into orderstatus (status) values ("Order is being handled");
insert into orderstatus (status) values ("Order cancelled");
insert into orderstatus (status) values ("Order unfinished");